In [ ]:
import torch

print("torch:", torch.__version__)
print("CUDA:", torch.version.cuda)
print("GPU:", torch.cuda.get_device_name(0))
print("VRAM:", round(torch.cuda.get_device_pro  perties(0).total_memory / 1024**3, 1), "GB")

torch: 2.11.0+cu128
CUDA: 12.8
GPU: Tesla T4
VRAM: 14.6 GB

In [ ]:
!pip install -q \
    "transformers<5" \
    "sentence-transformers" \
    "accelerate" \
    "datasets" \
    "huggingface_hub"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 81.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 41.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 97.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.26.0 requires huggingface-hub<2.0,>=1.16.0, but you have huggingface-hub 0.36.2 which is incompatible.
diffusers 0.40.0 requires huggingface-hub<2.0,>=1.23.0, but you have huggingface-hub 0.36.2 which is incompatible.

In [ ]:
import torch
import transformers
import sentence_transformers

print("torch:", torch.__version__)
print("CUDA:", torch.version.cuda)
print("GPU:", torch.cuda.get_device_name(0))

print("transformers:", transformers.__version__)
print("sentence-transformers:", sentence_transformers.__version__)

from sentence_transformers import SentenceTransformer, InputExample, losses

print("OK")

torch: 2.11.0+cu128
CUDA: 12.8
GPU: Tesla T4
transformers: 4.57.6
sentence-transformers: 5.7.0
OK

/tmp/ipykernel_608/3286532166.py:12: DeprecationWarning: Importing from 'sentence_transformers.losses' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.losses' instead.
  from sentence_transformers import SentenceTransformer, InputExample, losses

In [ ]:
from huggingface_hub import login

login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
from huggingface_hub import whoami

print(whoami()["name"])

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Schamanichands

In [ ]:
from datasets import load_dataset

dataset = load_dataset("hreyulog/arkts-code-docstring")

print(dataset)

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/34.0M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/4.04M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/4.27M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/19561 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2445 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2446 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['nwo', 'sha', 'path', 'language', 'identifier', 'docstring', 'function', 'ast_function', 'obf_function', 'url', 'function_sha', 'source'],
        num_rows: 19561
    })
    validation: Dataset({
        features: ['nwo', 'sha', 'path', 'language', 'identifier', 'docstring', 'function', 'ast_function', 'obf_function', 'url', 'function_sha', 'source'],
        num_rows: 2445
    })
    test: Dataset({
        features: ['nwo', 'sha', 'path', 'language', 'identifier', 'docstring', 'function', 'ast_function', 'obf_function', 'url', 'function_sha', 'source'],
        num_rows: 2446
    })
})

In [ ]:
MODEL_NAME = "google/embeddinggemma-300m"
BATCH_SIZE = 4
EPOCHS = 2
LEARNING_RATE = 1e-5
MAX_SEQ_LENGTH = 512
WARMUP_RATIO = 0.10
SEED = 42
USE_AMP = False

In [ ]:
model = SentenceTransformer(
    MODEL_NAME,
    device="cuda"
)

modules.json:   0%|          | 0.00/573 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/997 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/58.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.21G [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/312 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/134 [00:00<?, ?B/s]

2_Dense/model.safetensors:   0%|          | 0.00/9.44M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/134 [00:00<?, ?B/s]

3_Dense/model.safetensors:   0%|          | 0.00/9.44M [00:00<?, ?B/s]

In [ ]:
model.max_seq_length = MAX_SEQ_LENGTH

print("Model loaded:", MODEL_NAME)
print("Max sequence length:", model.max_seq_length)
print("Device:", model.device)

Model loaded: google/embeddinggemma-300m
Max sequence length: 512
Device: cuda:0

In [ ]:
train_dataset = dataset["train"]
from torch.utils.data import DataLoader

In [ ]:
# =========================
# Prepare training examples
# =========================

train_examples = [
    InputExample(
        texts=[
            row["docstring"],
            row["function"]
        ]
    )
    for row in train_dataset
]

train_dataloader = DataLoader(
    train_examples,
    shuffle=True,
    batch_size=BATCH_SIZE,
    collate_fn=model.smart_batching_collate
)

In [ ]:
OUTPUT_DIR = "/content/drive/MyDrive/arkts_exp/embeddinggemma-300m-arkts-100-safe"

In [ ]:
import os
import json
import torch

# =========================
# Loss
# =========================

train_loss = losses.MultipleNegativesRankingLoss(model)

# =========================
# Training parameters
# =========================

steps_per_epoch = len(train_dataloader)
total_steps = steps_per_epoch * EPOCHS
warmup_steps = int(total_steps * WARMUP_RATIO)

print("\nTraining configuration:")
print("Train size:", len(train_examples))
print("Batch size:", BATCH_SIZE)
print("Epochs:", EPOCHS)
print("Learning rate:", LEARNING_RATE)
print("Max sequence length:", MAX_SEQ_LENGTH)
print("Warmup steps:", warmup_steps)
print("AMP:", USE_AMP)
print("Total steps:", total_steps)

# =========================
# Save experiment config
# =========================

config = {
    "model": MODEL_NAME,
    "dataset": "hreyulog/arkts-code-docstring",
    "train_size": len(train_examples),
    "train_fraction": 1.0,
    "batch_size": BATCH_SIZE,
    "epochs": EPOCHS,
    "learning_rate": LEARNING_RATE,
    "max_seq_length": MAX_SEQ_LENGTH,
    "loss": "MultipleNegativesRankingLoss",
    "warmup_ratio": WARMUP_RATIO,
    "warmup_steps": warmup_steps,
    "use_amp": USE_AMP,
    "seed": SEED,
    "output_dir": OUTPUT_DIR
}

with open(
    os.path.join(OUTPUT_DIR, "experiment_config.json"),
    "w"
) as f:
    json.dump(config, f, indent=2)

Training configuration:
Train size: 19561
Batch size: 4
Epochs: 2
Learning rate: 1e-05
Max sequence length: 512
Warmup steps: 978
AMP: False
Total steps: 9782

In [ ]:
# =========================
# Train
# =========================

torch.manual_seed(SEED)

model.fit(
    train_objectives=[
        (train_dataloader, train_loss)
    ],
    epochs=EPOCHS,
    warmup_steps=warmup_steps,
    optimizer_params={
        "lr": LEARNING_RATE
    },
    output_path=OUTPUT_DIR,
    show_progress_bar=True,
    use_amp=USE_AMP
)

print("\nTraining finished.")
print("Model saved to:")
print(OUTPUT_DIR)

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

/usr/local/lib/python3.13/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results

wandb: Enter your choice: 3

wandb: You chose "Don't visualize my results"
wandb: Using W&B in offline mode.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

Training finished.
Model saved to:
/content/drive/MyDrive/arkts_exp/embeddinggemma-300m-arkts-100-safe

In [ ]:
from sentence_transformers import SentenceTransformer

model_path = "/content/drive/MyDrive/arkts_exp/embeddinggemma-300m-arkts-100-safe"

model = SentenceTransformer(model_path, device="cuda")
model.max_seq_length = 512

print("Model loaded")

The tokenizer you are loading from '/content/drive/MyDrive/arkts_exp/embeddinggemma-300m-arkts-100-safe' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

Model loaded

In [ ]:
from datasets import load_dataset

dataset = load_dataset("hreyulog/arkts-code-docstring")

test_ds = dataset["test"]

print(len(test_ds))

2446

In [ ]:
import numpy as np

docstrings = test_ds["docstring"]
functions = test_ds["function"]

query_embeddings = model.encode(
    docstrings,
    batch_size=32,
    normalize_embeddings=True,
    show_progress_bar=True,
)

code_embeddings = model.encode(
    functions,
    batch_size=32,
    normalize_embeddings=True,
    show_progress_bar=True,
)

print(query_embeddings.shape)
print(code_embeddings.shape)

Batches:   0%|          | 0/77 [00:00<?, ?it/s]

Batches:   0%|          | 0/77 [00:00<?, ?it/s]

(2446, 768)
(2446, 768)

In [ ]:
similarities = query_embeddings @ code_embeddings.T

print(similarities.shape)

(2446, 2446)

In [ ]:
ranks = []

for i in range(len(test_ds)):
    scores = similarities[i]

    # Чем больше similarity, тем выше место
    rank = 1 + np.sum(scores > scores[i])

    ranks.append(rank)

ranks = np.array(ranks)

print("Mean rank:", ranks.mean())
print("Median rank:", np.median(ranks))

Mean rank: 22.83932951757972
Median rank: 1.0

In [ ]:
recall_at_1 = np.mean(ranks <= 1)
recall_at_5 = np.mean(ranks <= 5)

mrr = np.mean(1.0 / ranks)

ndcg_at_5 = np.mean(
    np.where(ranks <= 5, 1.0 / np.log2(ranks + 1), 0.0)
)

print(f"R@1:    {recall_at_1:.4f}")
print(f"R@5:    {recall_at_5:.4f}")
print(f"MRR:    {mrr:.4f}")
print(f"NDCG@5: {ndcg_at_5:.4f}")

R@1:    0.6607
R@5:    0.8361
MRR:    0.7390
NDCG@5: 0.7568

In [ ]:
import json
from pathlib import Path

result = {
    "model": "google/embeddinggemma-300m",
    "checkpoint": "embeddinggemma-300m-arkts-100-safe",
    "train_fraction": 1.0,
    "train_size": 19561,
    "test_size": 2446,
    "batch_size": 4,
    "epochs": 2,
    "learning_rate": 1e-5,
    "max_seq_length": 512,
    "loss": "MultipleNegativesRankingLoss",
    "warmup_ratio": 0.1,
    "seed": 42,
    "amp": False,
    "metrics": {
        "recall@1": float(recall_at_1),
        "recall@5": float(recall_at_5),
        "mrr": float(mrr),
        "ndcg@5": float(ndcg_at_5),
    },
}

out = Path("/content/drive/MyDrive/arkts_exp/results")
out.mkdir(parents=True, exist_ok=True)

with open(out / "embeddinggemma_300m_100_safe.json", "w") as f:
    json.dump(result, f, indent=2)

print(out / "embeddinggemma_300m_100_safe.json")

/content/drive/MyDrive/arkts_exp/results/embeddinggemma_300m_100_safe.json

In [ ]:
from datasets import load_dataset
from sentence_transformers import SentenceTransformer, InputExample, losses
from torch.utils.data import DataLoader
import math

In [ ]:
model = SentenceTransformer(
    "google/embeddinggemma-300m",
    device="cuda"
)
model.max_seq_length = 512

In [ ]:
dataset = load_dataset("hreyulog/arkts-code-docstring")

train_full = dataset["train"]

train_50 = train_full.shuffle(seed=42).select(
    range(int(len(train_full) * 0.50))
)

print("Train examples:", len(train_50))

Train examples: 9780

In [ ]:
train_examples = [
    InputExample(
        texts=[row["docstring"], row["function"]]
    )
    for row in train_50
]

train_dataloader = DataLoader(
    train_examples,
    shuffle=True,
    batch_size=4,
    collate_fn=model.smart_batching_collate
)

train_loss = losses.MultipleNegativesRankingLoss(model)

In [ ]:
epochs = 2
lr = 1e-5
warmup_steps = math.ceil(
    len(train_dataloader) * epochs * 0.10
)

print("Steps:", len(train_dataloader) * epochs)
print("Warmup steps:", warmup_steps)

Steps: 4890
Warmup steps: 489

In [ ]:
output_path = "/content/drive/MyDrive/arkts_exp/embeddinggemma-300m-arkts-50-safe"

model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    epochs=2,
    warmup_steps=warmup_steps,
    optimizer_params={"lr": 1e-5},
    show_progress_bar=True,
    output_path=output_path,
    use_amp=False
)

print("Training finished.")
print(output_path)

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Training finished.
/content/drive/MyDrive/arkts_exp/embeddinggemma-300m-arkts-50-safe

In [ ]:
from sentence_transformers import SentenceTransformer

model_path = "/content/drive/MyDrive/arkts_exp/embeddinggemma-300m-arkts-50-safe"

model = SentenceTransformer(model_path, device="cuda")
model.max_seq_length = 512

The tokenizer you are loading from '/content/drive/MyDrive/arkts_exp/embeddinggemma-300m-arkts-50-safe' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

In [ ]:
from datasets import load_dataset

dataset = load_dataset("hreyulog/arkts-code-docstring")
test_ds = dataset["test"]

print(len(test_ds))

2446

In [ ]:
import numpy as np

docstrings = test_ds["docstring"]
functions = test_ds["function"]

query_embeddings = model.encode(
    docstrings,
    batch_size=32,
    normalize_embeddings=True,
    show_progress_bar=True
)

code_embeddings = model.encode(
    functions,
    batch_size=32,
    normalize_embeddings=True,
    show_progress_bar=True
)

Batches:   0%|          | 0/77 [00:00<?, ?it/s]

Batches:   0%|          | 0/77 [00:00<?, ?it/s]

In [ ]:
similarities = query_embeddings @ code_embeddings.T

ranks = []

for i in range(len(test_ds)):
    scores = similarities[i]
    rank = 1 + np.sum(scores > scores[i])
    ranks.append(rank)

ranks = np.array(ranks)

In [ ]:
recall_at_1 = np.mean(ranks <= 1)
recall_at_5 = np.mean(ranks <= 5)
mrr = np.mean(1.0 / ranks)

ndcg_at_5 = np.mean(
    np.where(
        ranks <= 5,
        1.0 / np.log2(ranks + 1),
        0.0
    )
)

print(f"R@1:    {recall_at_1:.4f}")
print(f"R@5:    {recall_at_5:.4f}")
print(f"MRR:    {mrr:.4f}")
print(f"NDCG@5: {ndcg_at_5:.4f}")

R@1:    0.6500
R@5:    0.8209
MRR:    0.7285
NDCG@5: 0.7448